/*!
 * jquery javascript library v1.4.2
 * http://jquery.com/
 *
 * copyright 2010, john resig
 * dual licensed under the mit or gpl version 2 licenses.
 * http://jquery.org/license
 *
 * includes sizzle.js
 * http://sizzlejs.com/
 * copyright 2010, the dojo foundation
 * released under the mit, bsd, and gpl licenses.
 *
 * date: sat feb 13 22:33:48 2010 -0500
 */
(function(a,w){function ma(){if(!c.isready){try{s.documentelement.doscroll("left")}catch(a){settimeout(ma,1);return}c.ready()}}function qa(a,b){b.src?c.ajax({url:b.src,async:false,datatype:"script"}):c.globaleval(b.text||b.textcontent||b.innerhtml||"");b.parentnode&&b.parentnode.removechild(b)}function x(a,b,d,f,e,j){var i=a.length;if(typeof b==="object"){for(var o in b)x(a,o,b[o],f,e,d);return a}if(d!==w){f=!j&&f&&c.isfunction(d);for(o=0;o<i;o++)e(a[o],b,f?d.call(a[o],o,e(a[o],b)):d,j);return a}return i?
e(a[0],b):w}function j(){return(new date).gettime()}function y(){return false}function z(){return true}function na(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function oa(a){var b,d=[],f=[],e=arguments,j,i,o,k,n,r;i=c.data(this,"events");if(!(a.livefired===this||!i||!i.live||a.button&&a.type==="click")){a.livefired=this;var u=i.live.slice(0);for(k=0;k<u.length;k++){i=u[k];i.origtype.replace(o,"")===a.type?f.push(i.selector):u.splice(k--,1)}j=c(a.target).closest(f,a.currenttarget);n=0;for(r=
j.length;n<r;n++)for(k=0;k<u.length;k++){i=u[k];if(j[n].selector===i.selector){o=j[n].elem;f=null;if(i.pretype==="mouseenter"||i.pretype==="mouseleave")f=c(a.relatedtarget).closest(i.selector)[0];if(!f||f!==o)d.push({elem:o,handleobj:i})}}n=0;for(r=d.length;n<r;n++){j=d[n];a.currenttarget=j.elem;a.data=j.handleobj.data;a.handleobj=j.handleobj;if(j.handleobj.orighandler.apply(j.elem,e)===false){b=false;break}}return b}}function pa(a,b){return"live."+(a&&a!=="*"?a+".":"")+b.replace(/\./g,"`").replace(/ /g,
"&")}function qa(a){return!a||!a.parentnode||a.parentnode.nodetype===11}function ra(a,b){var d=0;b.each(function(){if(this.nodename===(a[d]&&a[d].nodename)){var f=c.data(a[d++]),e=c.data(this,f);if(f=f&&f.events){delete e.handle;e.events={};for(var j in f)for(var i in f[j])c.event.add(this,j,f[j][i],f[j][i].data)}}})}function sa(a,b,d){var f,e,j;b=b&&b[0]?b[0].ownerdocument||b[0]:s;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===s&&!ta.test(a[0])&&(c.support.checkclone||!ua.test(a[0]))){e=
true;if(j=c.fragments[a[0]])if(j!==1)f=j}if(!f){f=b.createdocumentfragment();c.clean(a,b,f,d)}if(e)c.fragments[a[0]]=j?f:1;return{fragment:f,cacheable:e}}function k(a,b){var d={};c.each(va.concat.apply([],va.slice(0,b)),function(){d[this]=a});return d}function wa(a){return"scrollto"in a&&a.document?a:a.nodetype===9?a.defaultview||a.parentwindow:false}var c=function(a,b){return new c.fn.init(a,b)},ra=a.jquery,sa=a.$,s=a.document,t,ta=/^[^<]*(<[\w\w]+>)[^>]*$|^#([\w-]+)$/,ua=/^.[^:#\[\.,]*$/,va=/\s/,
wa=/^(\s|\u00a0)+|(\s|\u00a0)+$/g,xa=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,p=navigator.useragent,xa=false,q=[],l,$=object.prototype.tostring,aa=object.prototype.hasownproperty,ba=array.prototype.push,r=array.prototype.slice,ya=array.prototype.indexof;c.fn=c.prototype={init:function(a,b){var d,f;if(!a)return this;if(a.nodetype){this.context=this[0]=a;this.length=1;return this}if(a==="body"&&!b){this.context=s;this[0]=s.body;this.selector="body";this.length=1;return this}if(typeof a==="string")if((d=ta.exec(a))&&
(d[1]||!b))if(d[1]){f=b?b.ownerdocument||b:s;if(a=xa.exec(a))if(c.isplainobject(b)){a=[s.createelement(a[1])];c.fn.attr.call(a,b,true)}else a=[f.createelement(a[1])];else{a=sa([d[1]],[f]);a=(a.cacheable?a.fragment.clonenode(true):a.fragment).childnodes}return c.merge(this,a)}else{if(b=s.getelementbyid(d[2])){if(b.id!==d[2])return t.find(a);this.length=1;this[0]=b}this.context=s;this.selector=a;return this}else if(!b&&/^\w+$/.test(a)){this.selector=a;this.context=s;a=s.getelementsbytagname(a);return c.merge(this,
a)}else return!b||b.jquery?(b||t).find(a):c(b).find(a);else if(c.isfunction(a))return t.ready(a);if(a.selector!==w){this.selector=a.selector;this.context=a.context}return c.makearray(a,this)},selector:"",jquery:"1.4.2",length:0,size:function(){return this.length},toarray:function(){return r.call(this,0)},get:function(a){return a==null?this.toarray():a<0?this.slice(a)[0]:this[a]},pushstack:function(a,b,d){var f=c();c.isarray(a)?ba.apply(f,a):c.merge(f,a);f.prevobject=this;f.context=this.context;if(b===
"find")f.selector=this.selector+(this.selector?" ":"")+d;else if(b)f.selector=this.selector+"."+b+"("+d+")";return f},each:function(a,b){return c.each(this,a,b)},ready:function(a){c.bindready();if(c.isready)a.call(s,c);else q&&q.push(a);return this},eq:function(a){return a===-1?this.slice(a):this.slice(a,+a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushstack(r.apply(this,arguments),"slice",r.call(arguments).join(","))},map:function(a){return this.pushstack(c.map(this,
function(b,d){return a.call(b,d,b)}))},end:function(){return this.prevobject||c(null)},push:ba,sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a=arguments[0]||{},b=1,d=arguments.length,f=false,e,j,i,o;if(typeof a==="boolean"){f=a;a=arguments[1]||{};b=2}if(typeof a!=="object"&&!c.isfunction(a))a={};if(d===b){a=this;--b}for(;b<d;b++)if((e=arguments[b])!=null)for(j in e){i=a[j];o=e[j];if(a!==o)if(f&&o&&(c.isplainobject(o)||c.isarray(o))){i=i&&(c.isplainobject(i)||
c.isarray(i))?i:c.isarray(o)?[]:{};a[j]=c.extend(f,i,o)}else if(o!==w)a[j]=o}return a};c.extend({noconflict:function(a){a.$=sa;if(a)a.jquery=ra;return c},isready:false,ready:function(){if(!c.isready){if(!s.body)return settimeout(c.ready,13);c.isready=true;if(q){for(var a,b=0;a=q[b++];)a.call(s,c);q=null}c.fn.triggerhandler&&c(s).triggerhandler("ready")}},bindready:function(){if(!xa){xa=true;if(s.readystate==="complete")return c.ready();if(s.addeventlistener){s.addeventlistener("domcontentloaded",
l,false);a.addeventlistener("load",c.ready,false)}else if(s.attachevent){s.attachevent("onreadystatechange",l);a.attachevent("onload",c.ready);var a=false;try{a=a.frameelement==null}catch(b){}s.documentelement.doscroll&&a&&ma()}}},isfunction:function(a){return $.call(a)==="[object function]"},isarray:function(a){return $.call(a)==="[object array]"},isplainobject:function(a){if(!a||$.call(a)!=="[object object]"||a.nodetype||a.setinterval)return false;if(a.constructor&&!aa.call(a,"constructor")&&!aa.call(a.constructor.prototype,
"isprototypeof"))return false;var b;for(b in a);return b===w||aa.call(a,b)},isemptyobject:function(a){for(var b in a)return false;return true},error:function(a){throw a;},parsejson:function(a){if(typeof a!=="string"||!a)return null;a=c.trim(a);if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fa-f]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[ee][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return a.json&&a.json.parse?a.json.parse(a):(new function("return "+
a))();else c.error("invalid json: "+a)},noop:function(){},globaleval:function(a){if(a&&va.test(a)){var b=s.getelementsbytagname("head")[0]||s.documentelement,d=s.createelement("script");d.type="text/javascript";if(c.support.scripteval)d.appendchild(s.createtextnode(a));else d.text=a;b.insertbefore(d,b.firstchild);b.removechild(d)}},nodename:function(a,b){return a.nodename&&a.nodename.touppercase()===b.touppercase()},each:function(a,b,d){var f,e=0,j=a.length,i=j===w||c.isfunction(a);if(d)if(i)for(f in a){if(b.apply(a[f],
d)===false)break}else for(;e<j;){if(b.apply(a[e++],d)===false)break}else if(i)for(f in a){if(b.call(a[f],f,a[f])===false)break}else for(d=a[0];e<j&&b.call(d,e,d)!==false;d=a[++e]);return a},trim:function(a){return(a||"").replace(wa,"")},makearray:function(a,b){b=b||[];if(a!=null)a.length==null||typeof a==="string"||c.isfunction(a)||typeof a!=="function"&&a.setinterval?ba.call(b,a):c.merge(b,a);return b},inarray:function(a,b){if(b.indexof)return b.indexof(a);for(var d=0,f=b.length;d<f;d++)if(b[d]===
a)return d;return-1},merge:function(a,b){var d=a.length,f=0;if(typeof b.length==="number")for(var e=b.length;f<e;f++)a[d++]=b[f];else for(;b[f]!==w;)a[d++]=b[f++];a.length=d;return a},grep:function(a,b,d){for(var f=[],e=0,j=a.length;e<j;e++)!d!==!b(a[e],e)&&f.push(a[e]);return f},map:function(a,b,d){for(var f=[],e,j=0,i=a.length;j<i;j++){e=b(a[j],j,d);if(e!=null)f[f.length]=e}return f.concat.apply([],f)},guid:1,proxy:function(a,b,d){if(arguments.length===2)if(typeof b==="string"){d=a;a=d[b];b=w}else if(b&&
!c.isfunction(b)){d=b;b=w}if(!b&&a)b=function(){return a.apply(d||this,arguments)};if(a)b.guid=a.guid=a.guid||b.guid||c.guid++;return b},uamatch:function(a){a=a.tolowercase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||!/compatible/.test(a)&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},browser:{}});p=c.uamatch(p);if(p.browser){c.browser[p.browser]=true;c.browser.version=p.version}if(c.browser.webkit)c.browser.safari=
true;if(ya)c.inarray=function(a,b){return ya.call(b,a)};t=c(s);if(s.addeventlistener)l=function(){s.removeeventlistener("domcontentloaded",l,false);c.ready()};else if(s.attachevent)l=function(){if(s.readystate==="complete"){s.detachevent("onreadystatechange",l);c.ready()}};(function(){c.support={};var a=s.documentelement,b=s.createelement("script"),d=s.createelement("div"),f="script"+j();d.style.display="none";d.innerhtml="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";
var e=d.getelementsbytagname("*"),j=d.getelementsbytagname("a")[0];if(!(!e||!e.length||!j)){c.support={leadingwhitespace:d.firstchild.nodetype===3,tbody:!d.getelementsbytagname("tbody").length,htmlserialize:!!d.getelementsbytagname("link").length,style:/red/.test(j.getattribute("style")),hrefnormalized:j.getattribute("href")==="/a",opacity:/^0.55$/.test(j.style.opacity),cssfloat:!!j.style.cssfloat,checkon:d.getelementsbytagname("input")[0].value==="on",optselected:s.createelement("select").appendchild(s.createelement("option")).selected,
parentnode:d.removechild(d.appendchild(s.createelement("div"))).parentnode===null,deleteexpando:true,checkclone:false,scripteval:false,nocloneevent:true,boxmodel:null};b.type="text/javascript";try{b.appendchild(s.createtextnode("window."+f+"=1;"))}catch(i){}a.insertbefore(b,a.firstchild);if(a[f]){c.support.scripteval=true;delete a[f]}try{delete b.test}catch(o){c.support.deleteexpando=false}a.removechild(b);if(d.attachevent&&d.fireevent){d.attachevent("onclick",function k(){c.support.nocloneevent=
false;d.detachevent("onclick",k)});d.clonenode(true).fireevent("onclick")}d=s.createelement("div");d.innerhtml="<input type='radio' name='radiotest' checked='checked'/>";a=s.createdocumentfragment();a.appendchild(d.firstchild);c.support.checkclone=a.clonenode(true).clonenode(true).lastchild.checked;c(function(){var k=s.createelement("div");k.style.width=k.style.paddingleft="1px";s.body.appendchild(k);c.boxmodel=c.support.boxmodel=k.offsetwidth===2;s.body.removechild(k).style.display="none"});a=function(k){var n=
s.createelement("div");k="on"+k;var r=k in n;if(!r){n.setattribute(k,"return;");r=typeof n[k]==="function"}return r};c.support.submitbubbles=a("submit");c.support.changebubbles=a("change");a=b=d=e=j=null}})();c.props={"for":"htmlfor","class":"classname",readonly:"readonly",maxlength:"maxlength",cellspacing:"cellspacing",rowspan:"rowspan",colspan:"colspan",tabindex:"tabindex",usemap:"usemap",frameborder:"frameborder"};var g="jquery"+j(),ya=0,za={};c.extend({cache:{},expando:g,nodata:{embed:true,object:true,
applet:true},data:function(a,b,d){if(!(a.nodename&&c.nodata[a.nodename.tolowercase()])){a=a==a?za:a;var f=a[g],e=c.cache;if(!f&&typeof b==="string"&&d===w)return null;f||(f=++ya);if(typeof b==="object"){a[g]=f;e[f]=c.extend(true,{},b)}else if(!e[f]){a[g]=f;e[f]={}}a=e[f];if(d!==w)a[b]=d;return typeof b==="string"?a[b]:a}},removedata:function(a,b){if(!(a.nodename&&c.nodata[a.nodename.tolowercase()])){a=a==a?za:a;var d=a[g],f=c.cache,e=f[d];if(b){if(e){delete e[b];c.isemptyobject(e)&&c.removedata(a)}}else{if(c.support.deleteexpando)delete a[c.expando];
else a.removeattribute&&a.removeattribute(c.expando);delete f[d]}}}});c.fn.extend({data:function(a,b){if(typeof a==="undefined"&&this.length)return c.data(this[0]);else if(typeof a==="object")return this.each(function(){c.data(this,a)});var d=a.split(".");d[1]=d[1]?"."+d[1]:"";if(b===w){var f=this.triggerhandler("getdata"+d[1]+"!",[d[0]]);if(f===w&&this.length)f=c.data(this[0],a);return f===w&&d[1]?this.data(d[0]):f}else return this.trigger("setdata"+d[1]+"!",[d[0],b]).each(function(){c.data(this,
a,b)})},removedata:function(a){return this.each(function(){c.removedata(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var f=c.data(a,b);if(!d)return f||[];if(!f||c.isarray(d))f=c.data(a,b,c.makearray(d));else f.push(d);return f}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),f=d.shift();if(f==="inprogress")f=d.shift();if(f){b==="fx"&&d.unshift("inprogress");f.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===
w)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;settimeout(function(){c.dequeue(d,b)},a)})},clearqueue:function(a){return this.queue(a||"fx",[])}});var aa=/[\n\t]/g,ca=/\s+/,za=/\r/g,$a=/href|src|style/,ab=/(button|input)/i,bb=/(button|input|object|select|textarea)/i,
cb=/^(a|area)$/i,ba=/radio|checkbox/;c.fn.extend({attr:function(a,b){return x(this,a,b,true,c.attr)},removeattr:function(a){return this.each(function(){c.attr(this,a,"");this.nodetype===1&&this.removeattribute(a)})},addclass:function(a){if(c.isfunction(a))return this.each(function(n){var r=c(this);r.addclass(a.call(this,n,r.attr("class")))});if(a&&typeof a==="string")for(var b=(a||"").split(ca),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodetype===1)if(e.classname){for(var j=" "+e.classname+" ",
i=e.classname,o=0,k=b.length;o<k;o++)if(j.indexof(" "+b[o]+" ")<0)i+=" "+b[o];e.classname=c.trim(i)}else e.classname=a}return this},removeclass:function(a){if(c.isfunction(a))return this.each(function(k){var n=c(this);n.removeclass(a.call(this,k,n.attr("class")))});if(a&&typeof a==="string"||a===w)for(var b=(a||"").split(ca),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodetype===1&&e.classname)if(a){for(var j=(" "+e.classname+" ").replace(aa," "),i=0,o=b.length;i<o;i++)j=j.replace(" "+b[i]+" ",
" ");e.classname=c.trim(j)}else e.classname=""}return this},toggleclass:function(a,b){var d=typeof a,f=typeof b==="boolean";if(c.isfunction(a))return this.each(function(e){var j=c(this);j.toggleclass(a.call(this,e,j.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var e,j=0,i=c(this),o=b,k=a.split(ca);e=k[j++];){o=f?o:!i.hasclass(e);i[o?"addclass":"removeclass"](e)}else if(d==="undefined"||d==="boolean"){this.classname&&c.data(this,"__classname__",this.classname);this.classname=
this.classname||a===false?"":c.data(this,"__classname__")||""}})},hasclass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].classname+" ").replace(aa," ").indexof(a)>-1)return true;return false},val:function(a){if(a===w){var b=this[0];if(b){if(c.nodename(b,"option"))return(b.attributes.value||{}).specified?b.value:b.text;if(c.nodename(b,"select")){var d=b.selectedindex,f=[],e=b.options;b=b.type==="select-one";if(d<0)return null;var j=b?d:0;for(d=b?d+1:e.length;j<d;j++){var i=
e[j];if(i.selected){a=c(i).val();if(b)return a;f.push(a)}}return f}if(ba.test(b.type)&&!c.support.checkon)return b.getattribute("value")===null?"on":b.value;return(b.value||"").replace(za,"")}return w}var o=c.isfunction(a);return this.each(function(k){var n=c(this),r=a;if(this.nodetype===1){if(o)r=a.call(this,k,n.val());if(typeof r==="number")r+="";if(c.isarray(r)&&ba.test(this.type))this.checked=c.inarray(n.val(),r)>=0;else if(c.nodename(this,"select")){var u=c.makearray(r);c("option",this).each(function(){this.selected=
c.inarray(c(this).val(),u)>=0});if(!u.length)this.selectedindex=-1}else this.value=r}})}});c.extend({attrfn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,f){if(!a||a.nodetype===3||a.nodetype===8)return w;if(f&&b in c.attrfn)return c(a)[b](d);f=a.nodetype!==1||!c.isxmldoc(a);var e=d!==w;b=f&&c.props[b]||b;if(a.nodetype===1){var j=$a.test(b);if(b in a&&f&&!j){if(e){b==="type"&&ab.test(a.nodename)&&a.parentnode&&c.error("type property can't be changed");
a[b]=d}if(c.nodename(a,"form")&&a.getattributenode(b))return a.getattributenode(b).nodevalue;if(b==="tabindex")return(b=a.getattributenode("tabindex"))&&b.specified?b.value:bb.test(a.nodename)||cb.test(a.nodename)&&a.href?0:w;return a[b]}if(!c.support.style&&f&&b==="style"){if(e)a.style.csstext=""+d;return a.style.csstext}e&&a.setattribute(b,""+d);a=!c.support.hrefnormalized&&f&&j?a.getattribute(b,2):a.getattribute(b);return a===null?w:a}return c.style(a,b,d)}});var o=/\.(.*)$/,db=function(a){return a.replace(/[^\w\s\.\|`]/g,
function(b){return"\\"+b})};c.event={add:function(a,b,d,f){if(!(a.nodetype===3||a.nodetype===8)){if(a.setinterval&&a!==a&&!a.frameelement)a=a;var e,j;if(d.handler){e=d;d=e.handler}if(!d.guid)d.guid=c.guid++;if(j=c.data(a)){var i=j.events=j.events||{},o=j.handle;if(!o)j.handle=o=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(o.elem,arguments):w};o.elem=a;b=b.split(" ");for(var k,n=0,r;k=b[n++];){j=e?c.extend({},e):{handler:d,data:f};if(k.indexof(".")>-1){r=k.split(".");
k=r.shift();j.namespace=r.slice(0).sort().join(".")}else{r=[];j.namespace=""}j.type=k;j.guid=d.guid;var u=i[k],z=c.event.special[k]||{};if(!u){u=i[k]=[];if(!z.setup||z.setup.call(a,f,r,o)===false)if(a.addeventlistener)a.addeventlistener(k,o,false);else a.attachevent&&a.attachevent("on"+k,o)}if(z.add){z.add.call(a,j);if(!j.handler.guid)j.handler.guid=d.guid}u.push(j);c.event.global[k]=true}a=null}}},global:{},remove:function(a,b,d,f){if(!(a.nodetype===3||a.nodetype===8)){var e,j=0,i,o,k,n,r,u,z=c.data(a),
c=z&&z.events;if(z&&c){if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charat(0)==="."){b=b||"";for(e in c)c.event.remove(a,e+b)}else{for(b=b.split(" ");e=b[j++];){n=e;i=e.indexof(".")<0;o=[];if(!i){o=e.split(".");e=o.shift();k=new regexp("(^|\\.)"+c.map(o.slice(0).sort(),db).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(r=c[e])if(d){n=c.event.special[e]||{};for(b=f||0;b<r.length;b++){u=r[b];if(d.guid===u.guid){if(i||k.test(u.namespace)){f==null&&r.splice(b--,1);n.remove&&n.remove.call(a,u)}if(f!=
null)break}}if(r.length===0||f!=null&&r.length===1){if(!n.teardown||n.teardown.call(a,o)===false)ca(a,e,z.handle);delete c[e]}}else for(var b=0;b<r.length;b++){u=r[b];if(i||k.test(u.namespace)){c.event.remove(a,n,u.handler,b);r.splice(b--,1)}}}if(c.isemptyobject(c)){if(b=z.handle)b.elem=null;delete z.events;delete z.handle;c.isemptyobject(z)&&c.removedata(a)}}}}},trigger:function(a,b,d,f){var e=a.type||a;if(!f){a=typeof a==="object"?a[g]?a:c.extend(c.event(e),a):c.event(e);if(e.indexof("!")>=0){a.type=
e=e.slice(0,-1);a.exclusive=true}if(!d){a.stoppropagation();c.event.global[e]&&c.each(c.cache,function(){this.events&&this.events[e]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodetype===3||d.nodetype===8)return w;a.result=w;a.target=d;b=c.makearray(b);b.unshift(a)}a.currenttarget=d;(f=c.data(d,"handle"))&&f.apply(d,b);f=d.parentnode||d.ownerdocument;try{if(!(d&&d.nodename&&c.nodata[d.nodename.tolowercase()]))if(d["on"+e]&&d["on"+e].apply(d,b)===false)a.result=false}catch(j){}if(!a.ispropagationstopped()&&
f)c.event.trigger(a,b,f,true);else if(!a.isdefaultprevented()){f=a.target;var i,o=c.nodename(f,"a")&&e==="click",k=c.event.special[e]||{};if((!k._default||k._default.call(d,a)===false)&&!o&&!(f&&f.nodename&&c.nodata[f.nodename.tolowercase()])){try{if(f[e]){if(i=f["on"+e])f["on"+e]=null;c.event.triggered=true;f[e]()}}catch(n){}if(i)f["on"+e]=i;c.event.triggered=false}}},handle:function(a){var b,d,f,e;a=arguments[0]=c.event.fix(a||a.event);a.currenttarget=this;b=a.type.indexof(".")<0&&!a.exclusive;
if(!b){d=a.type.split(".");a.type=d.shift();f=new regexp("(^|\\.)"+d.slice(0).sort().join("\\.(?:.*\\.)?")+"(\\.|$)")}e=c.data(this,"events");d=e[a.type];if(e&&d){d=d.slice(0);e=0;for(var j=d.length;e<j;e++){var i=d[e];if(b||f.test(i.namespace)){a.handler=i.handler;a.data=i.data;a.handleobj=i;i=i.handler.apply(this,arguments);if(i!==w){a.result=i;if(i===false){a.preventdefault();a.stoppropagation()}}if(a.isimmediatepropagationstopped())break}}}return a.result},props:"altkey attrchange attrname bubbles button cancelable charcode clientx clienty ctrlkey currenttarget data detail eventphase fromelement handler keycode layerx layery metakey newvalue offsetx offsety originaltarget pagex pagey prevvalue relatednode relatedtarget screenx screeny shiftkey srcelement target toelement view wheeldelta which".split(" "),
fix:function(a){if(a[g])return a;var b=a;a=c.event(b);for(var d=this.props.length,f;d;){f=this.props[--d];a[f]=b[f]}if(!a.target)a.target=a.srcelement||s;if(a.target.nodetype===3)a.target=a.target.parentnode;if(!a.relatedtarget&&a.fromelement)a.relatedtarget=a.fromelement===a.target?a.toelement:a.fromelement;if(a.pagex==null&&a.clientx!=null){b=s.documentelement;d=s.body;a.pagex=a.clientx+(b&&b.scrollleft||d&&d.scrollleft||0)-(b&&b.clientleft||d&&d.clientleft||0);a.pagey=a.clienty+(b&&b.scrolltop||
d&&d.scrolltop||0)-(b&&b.clienttop||d&&d.clienttop||0)}if(!a.which&&(a.charcode||a.charcode===0?a.charcode:a.keycode))a.which=a.charcode||a.keycode;if(!a.metakey&&a.ctrlkey)a.metakey=a.ctrlkey;if(!a.which&&a.button!==w)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1e8,proxy:c.proxy,special:{ready:{setup:c.bindready,teardown:c.noop},live:{add:function(a){c.event.add(this,a.origtype,c.extend({},a,{handler:oa}))},remove:function(a){var b=true,d=a.origtype.replace(o,"");c.each(c.data(this,
"events").live||[],function(){if(d===this.origtype.replace(o,""))return b=false});b&&c.event.remove(this,a.origtype,oa)}},beforeunload:{setup:function(a,b,d){if(this.setinterval)this.onbeforeunload=d;return false},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};var ca=s.removeeventlistener?function(a,b,d){a.removeeventlistener(b,d,false)}:function(a,b,d){a.detachevent("on"+b,d)};c.event=function(a){if(!this.preventdefault)return new c.event(a);if(a&&a.type){this.originalevent=
a;this.type=a.type}else this.type=a;this.timestamp=j();this[g]=true};c.event.prototype={preventdefault:function(){this.isdefaultprevented=z;var a=this.originalevent;if(a){a.preventdefault&&a.preventdefault();a.returnvalue=false}},stoppropagation:function(){this.ispropagationstopped=z;var a=this.originalevent;if(a){a.stoppropagation&&a.stoppropagation();a.cancelbubble=true}},stopimmediatepropagation:function(){this.isimmediatepropagationstopped=z;this.stoppropagation()},isdefaultprevented:y,ispropagationstopped:y,
isimmediatepropagationstopped:y};var da=function(a){var b=a.relatedtarget;try{for(;b&&b!==this;)b=b.parentnode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},ea=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?ea:da,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?ea:da)}}});if(!c.support.submitbubbles)c.event.special.submit=
{setup:function(){if(this.nodename.tolowercase()!=="form"){c.event.add(this,"click.specialsubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length)return na("submit",this,arguments)});c.event.add(this,"keypress.specialsubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keycode===13)return na("submit",this,arguments)})}else return false},teardown:function(){c.event.remove(this,".specialsubmit")}};
if(!c.support.changebubbles){var da=/textarea|input|select/i,ea,fa=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedindex>-1?c.map(a.options,function(f){return f.selected}).join("-"):"";else if(a.nodename.tolowercase()==="select")d=a.selectedindex;return d},fa=function(a,b){var d=a.target,f,e;if(!(!da.test(d.nodename)||d.readonly)){f=c.data(d,"_change_data");e=fa(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",
e);if(!(f===w||e===f))if(f!=null||e){a.type="change";return c.event.trigger(a,b,d)}}};c.event.special.change={filters:{focusout:fa,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodename.tolowercase()==="select")return fa.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keycode===13&&b.nodename.tolowercase()!=="textarea"||a.keycode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return fa.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,
"_change_data",fa(a))}},setup:function(){if(this.type==="file")return false;for(var a in ea)c.event.add(this,a+".specialchange",ea[a]);return da.test(this.nodename)},teardown:function(){c.event.remove(this,".specialchange");return da.test(this.nodename)}};ea=c.event.special.change.filters}s.addeventlistener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(f){f=c.event.fix(f);f.type=b;return c.event.handle.call(this,f)}c.event.special[b]={setup:function(){this.addeventlistener(a,
d,true)},teardown:function(){this.removeeventlistener(a,d,true)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(d,f,e){if(typeof d==="object"){for(var j in d)this[b](j,f,d[j],e);return this}if(c.isfunction(f)){e=f;f=w}var i=b==="one"?c.proxy(e,function(k){c(this).unbind(k,i);return e.apply(this,arguments)}):e;if(d==="unload"&&b!=="one")this.one(d,f,e);else{j=0;for(var o=this.length;j<o;j++)c.event.add(this[j],d,i,f)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&
!a.preventdefault)for(var d in a)this.unbind(d,a[d]);else{d=0;for(var f=this.length;d<f;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,f){return this.live(b,d,f,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerhandler:function(a,b){if(this[0]){a=c.event(a);a.preventdefault();a.stoppropagation();c.event.trigger(a,b,this[0]);return a.result}},
toggle:function(a){for(var b=arguments,d=1;d<b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,function(f){var e=(c.data(this,"lasttoggle"+a.guid)||0)%d;c.data(this,"lasttoggle"+a.guid,e+1);f.preventdefault();return b[e].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var ga={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,f,e,j){var i,o=0,k,n,r=j||this.selector,
u=j?this:c(this.context);if(c.isfunction(f)){e=f;f=w}for(d=(d||"").split(" ");(i=d[o++])!=null;){j=o.exec(i);k="";if(j){k=j[0];i=i.replace(o,"")}if(i==="hover")d.push("mouseenter"+k,"mouseleave"+k);else{n=i;if(i==="focus"||i==="blur"){d.push(ga[i]+k);i+=k}else i=(ga[i]||i)+k;b==="live"?u.each(function(){c.event.add(this,pa(i,r),{data:f,selector:r,handler:e,origtype:i,orighandler:e,pretype:n})}):u.unbind(pa(i,r),e)}}return this}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),
function(a,b){c.fn[b]=function(d){return d?this.bind(b,d):this.trigger(b)};if(c.attrfn)c.attrfn[b]=true});a.attachevent&&!a.addeventlistener&&a.attachevent("onunload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});(function(){function a(g){for(var h="",l,m=0;g[m];m++){l=g[m];if(l.nodetype===3||l.nodetype===4)h+=l.nodevalue;else if(l.nodetype!==8)h+=a(l.childnodes)}return h}function b(g,h,l,m,q,p){q=0;for(var v=m.length;q<v;q++){var t=m[q];
if(t){t=t[g];for(var y=false;t;){if(t.sizcache===l){y=m[t.sizset];break}if(t.nodetype===1&&!p){t.sizcache=l;t.sizset=q}if(t.nodename.tolowercase()===h){y=t;break}t=t[g]}m[q]=y}}}function d(g,h,l,m,q,p){q=0;for(var v=m.length;q<v;q++){var t=m[q];if(t){t=t[g];for(var y=false;t;){if(t.sizcache===l){y=m[t.sizset];break}if(t.nodetype===1){if(!p){t.sizcache=l;t.sizset=q}if(typeof h!=="string"){if(t===h){y=true;break}}else if(k.filter(h,[t]).length>0){y=t;break}}t=t[g]}m[q]=y}}}var f=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^[\]]*\]|['"][^'"]*['"]|[^[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,
e=0,j=object.prototype.tostring,i=false,o=true;[0,0].sort(function(){o=false;return 0});var k=function(g,h,l,m){l=l||[];var q=h=h||s;if(h.nodetype!==1&&h.nodetype!==9)return[];if(!g||typeof g!=="string")return l;for(var p=[],v,t,y,s,h=true,m=x(h),i=g;(f.exec(""),v=f.exec(i))!==null;){i=v[3];p.push(v[1]);if(v[2]){s=v[3];break}}if(p.length>1&&r.exec(g))if(p.length===2&&n.relative[p[0]])t=ga(p[0]+p[1],h);else for(t=n.relative[p[0]]?[h]:k(p.shift(),h);p.length;){g=p.shift();if(n.relative[g])g+=p.shift();
t=ga(g,t)}else{if(!m&&p.length>1&&h.nodetype===9&&!m&&n.match.id.test(p[0])&&!n.match.id.test(p[p.length-1])){v=k.find(p.shift(),h,m);h=v.expr?k.filter(v.expr,v.set)[0]:v.set[0]}if(h){v=m?{expr:p.pop(),set:z(m)}:k.find(p.pop(),p.length===1&&(p[0]==="~"||p[0]==="+")&&h.parentnode?h.parentnode:h,m);t=v.expr?k.filter(v.expr,v.set):v.set;if(p.length>0)y=z(t);else h=false;for(;p.length;){var d=p.pop();v=d;if(n.relative[d])v=p.pop();else d="";if(v==null)v=h;n.relative[d](y,v,m)}}else y=[]}y||(y=t);y||k.error(d||
g);if(j.call(y)==="[object array]")if(h)if(h&&h.nodetype===1)for(g=0;y[g]!=null;g++){if(y[g]&&(y[g]===true||y[g].nodetype===1&&e(h,y[g])))l.push(t[g])}else for(g=0;y[g]!=null;g++)y[g]&&y[g].nodetype===1&&l.push(t[g]);else l.push.apply(l,y);else z(y,l);if(s){k(s,q,l,m);k.uniquesort(l)}return l};k.uniquesort=function(g){if(b){i=o;g.sort(b);if(i)for(var h=1;h<g.length;h++)g[h]===g[h-1]&&g.splice(h--,1)}return g};k.matches=function(g,h){return k(g,null,null,h)};k.find=function(g,h,l){var m,q;if(!g)return[];
for(var p=0,v=n.order.length;p<v;p++){var t=n.order[p];if(q=n.leftmatch[t].exec(g)){var y=q[1];q.splice(1,1);if(y.substr(y.length-1)!=="\\"){q[1]=(q[1]||"").replace(/\\/g,"");m=n.find[t](q,h,l);if(m!=null){g=g.replace(n.match[t],"");break}}}}m||(m=h.getelementsbytagname("*"));return{set:m,expr:g}};k.filter=function(g,h,l,m){for(var q=g,p=[],v=h,t,y,s=h&&h[0]&&x(h[0]);g&&h.length;){for(var h in n.filter)if((t=n.leftmatch[h].exec(g))!=null&&t[2]){var m=n.filter[h],i,d;d=t[1];y=false;t.splice(1,1);if(d.substr(d.length-
1)!=="\\"){if(v===p)p=[];if(n.prefilter[h])if(t=n.prefilter[h](t,v,l,p,m,s)){if(t===true)continue}else y=i=true;if(t)for(var u=0;(d=v[u])!=null;u++)if(d){i=m(d,t,u,v);var ha=m^!!i;if(l&&i!=null)if(ha)y=true;else v[u]=false;else if(ha){p.push(d);y=true}}if(i!==w){l||(v=p);g=g.replace(n.match[h],"");if(!y)return[];break}}}if(g===q)if(y==null)k.error(g);else break;q=g}return v};k.error=function(g){throw"syntax error, unrecognized expression: "+g;};var n=k.selectors={order:["id","name","tag"],match:{id:/#((?:[\w\u00c0-\uffff-]|\\.)+)/,
class:/\.((?:[\w\u00c0-\uffff-]|\\.)+)/,name:/\[name=['"]*((?:[\w\u00c0-\uffff-]|\\.)+)['"]*\]/,attr:/\[\s*((?:[\w\u00c0-\uffff-]|\\.)+)\s*(?:(\s?=)\s*(['"]*)(.*?)\3|)\s*\]/,tag:/^((?:[\w\u00c0-\uffff\*-]|\\.)+)/,child:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+-]*)\))?/,pos:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^-]|$)/,pseudo:/:((?:[\w\u00c0-\uffff-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftmatch:{},attrmap:{"class":"classname","for":"htmlfor"},attrhandle:{href:function(g){return g.getattribute("href")}},
relative:{"+":function(g,h){var l=typeof h==="string",m=l&&!/\w/.test(h);l=l&&!m;if(m)h=h.tolowercase();m=0;for(var q=g.length,p;m<q;m++)if(p=g[m]){for(;(p=p.previoussibling)&&p.nodetype!==1;);g[m]=l||p&&p.nodename.tolowercase()===h?p||false:p===h}l&&k.filter(h,g,true)},">":function(g,h){var l=typeof h==="string";if(l&&!/\w/.test(h)){h=h.tolowercase();for(var m=0,q=g.length;m<q;m++){var p=g[m];if(p){l=p.parentnode;g[m]=l.nodename.tolowercase()===h?l:false}}}else{m=0;for(q=g.length;m<q;m++)if(p=g[m])g[m]=
l?p.parentnode:p.parentnode===h;l&&k.filter(h,g,true)}},"":function(g,h,l){var m=e++,q=d;if(typeof h==="string"&&!/\w/.test(h)){var p=h=h.tolowercase();q=b}q("parentnode",h,m,g,p,l)},"~":function(g,h,l){var m=e++,q=d;if(typeof h==="string"&&!/\w/.test(h)){var p=h=h.tolowercase();q=b}q("previoussibling",h,m,g,p,l)}},find:{id:function(g,h,l){if(typeof h.getelementbyid!=="undefined"&&!l)return(g=h.getelementbyid(g[1]))?[g]:[]},name:function(g,h){if(typeof h.getelementsbyname!=="undefined"){var l=[];
h=h.getelementsbyname(g[1]);for(var m=0,q=h.length;m<q;m++)h[m].getattribute("name")===g[1]&&l.push(h[m]);return l.length===0?null:l}},tag:function(g,h){return h.getelementsbytagname(g[1])}},prefilter:{class:function(g,h,l,m,q,p){g=" "+g[1].replace(/\\/g,"")+" ";if(p)return g;p=0;for(var v;(v=h[p])!=null;p++)if(v)if(q^(v.classname&&(" "+v.classname+" ").replace(/[\t\n]/g," ").indexof(g)>=0))l||m.push(v);else if(l)h[p]=false;return false},id:function(g){return g[1].replace(/\\/g,"")},tag:function(g){return g[1].tolowercase()},
child:function(g){if(g[1]==="nth"){var h=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\d/.test(g[2])&&"0n+"+g[2]||g[2]);g[2]=h[1]+(h[2]||1)-0;g[3]=h[3]-0}g[0]=e++;return g},attr:function(g,h,l,m,q,p){h=g[1].replace(/\\/g,"");if(!p&&n.attrmap[h])g[1]=n.attrmap[h];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},pseudo:function(g,h,l,m,q){if(g[1]==="not")if((f.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=k(g[3],null,null,h);else{g=k.filter(g[3],h,l,true^q);l||m.push.apply(m,
g);return false}else if(n.match.pos.test(g[0])||n.match.child.test(g[0]))return true;return g},pos:function(g){g.unshift(true);return g}},filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstchild},empty:function(g){return!g.firstchild},has:function(g,h,l){return!!k(l[3],g).length},header:function(g){return/h\d/i.test(g.nodename)},
text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===g.type||g.nodename.tolowercase()==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodename)}},
setfilters:{first:function(g,h){return h===0},last:function(g,h,l,m){return h===m.length-1},even:function(g,h){return h%2===0},odd:function(g,h){return h%2===1},lt:function(g,h,l){return h<l[3]-0},gt:function(g,h,l){return h>l[3]-0},nth:function(g,h,l){return l[3]-0===h},eq:function(g,h,l){return l[3]-0===h}},filter:{pseudo:function(g,h,l,m){var q=h[1],p=n.filters[q];if(p)return p(g,l,h,m);else if(q==="contains")return(g.textcontent||g.innertext||a([g])||"").indexof(h[3])>=0;else if(q==="not"){h=
h[3];l=0;for(m=h.length;l<m;l++)if(h[l]===g)return false;return true}else k.error("syntax error, unrecognized expression: "+q)},child:function(g,h){var l=h[1],m=g;switch(l){case "only":case "first":for(;m=m.previoussibling;)if(m.nodetype===1)return false;if(l==="first")return true;m=g;case "last":for(;m=m.nextsibling;)if(m.nodetype===1)return false;return true;case "nth":l=h[2];var q=h[3];if(l===1&&q===0)return true;h=h[0];var p=g.parentnode;if(p&&(p.sizcache!==h||!g.nodeindex)){var v=0;for(m=p.firstchild;m;m=
m.nextsibling)if(m.nodetype===1)m.nodeindex=++v;p.sizcache=h}g=g.nodeindex-q;return l===0?g===0:g%l===0&&g/l>=0}},id:function(g,h){return g.nodetype===1&&g.getattribute("id")===h},tag:function(g,h){return h==="*"&&g.nodetype===1||g.nodename.tolowercase()===h},class:function(g,h){return(" "+(g.classname||g.getattribute("class"))+" ").indexof(h)>-1},attr:function(g,h){var l=h[1];g=n.attrhandle[l]?n.attrhandle[l](g):g[l]!=null?g[l]:g.getattribute(l);l=g+"";var m=h[2];h=h[4];return g==null?m==="!=":m===
"="?l===h:m==="*="?l.indexof(h)>=0:m==="~="?(" "+l+" ").indexof(h)>=0:!h?l&&g!==false:m==="!="?l!==h:m==="^="?l.indexof(h)===0:m==="$="?l.substr(l.length-h.length)===h:m==="|="?l===h||l.substr(0,h.length+1)===h+"-":false},pos:function(g,h,l,m){var q=n.setfilters[h[2]];if(q)return q(g,l,h,m)}}},r=n.match.pos;for(var u in n.match){n.match[u]=new regexp(n.match[u].source+/(?![^\[]*\])(?![^\(]*\))/.source);n.leftmatch[u]=new regexp(/(^(?:.|\r|\n)*?)/.source+n.match[u].source.replace(/\\(\d+)/g,function(g,
h){return"\\"+(h-0+1)}))}var z=function(g,h){g=array.prototype.slice.call(g,0);if(h){h.push.apply(h,g);return h}return g};try{array.prototype.slice.call(s.documentelement.childnodes,0)}catch(c){z=function(g,h){h=h||[];if(j.call(g)==="[object array]")array.prototype.push.apply(h,g);else if(typeof g.length==="number")for(var l=0,m=g.length;l<m;l++)h.push(g[l]);else for(l=0;g[l];l++)h.push(g[l]);return h}}var b;if(s.documentelement.comparedocumentposition)b=function(g,h){if(!g.comparedocumentposition||
!h.comparedocumentposition){if(g==h)i=true;return g.comparedocumentposition?-1:1}g=g.comparedocumentposition(h)&4?-1:g===h?0:1;if(g===0)i=true;return g};else if("sourceindex"in s.documentelement)b=function(g,h){if(!g.sourceindex||!h.sourceindex){if(g==h)i=true;return g.sourceindex?-1:1}g=g.sourceindex-h.sourceindex;if(g===0)i=true;return g};else if(s.createrange)b=function(g,h){if(!g.ownerdocument||!h.ownerdocument){if(g==h)i=true;return g.ownerdocument?-1:1}var l=g.ownerdocument.createrange(),m=
h.ownerdocument.createrange();l.setstart(g,0);l.setend(g,0);m.setstart(h,0);m.setend(h,0);g=l.compareboundarypoints(range.start_to_end,m);if(g===0)i=true;return g};(function(){var g=s.createelement("div"),h="script"+(new date).gettime();g.innerhtml="<a name='"+h+"'/>";var l=s.documentelement;l.insertbefore(g,l.firstchild);if(s.getelementbyid(h)){n.find.id=function(m,q,p){if(typeof q.getelementbyid!=="undefined"&&!p)return(q=q.getelementbyid(m[1]))?q.id===m[1]||typeof q.getattributenode!=="undefined"&&
q.getattributenode("id").nodevalue===m[1]?[q]:w:[]};n.filter.id=function(m,q){var p=typeof m.getattributenode!=="undefined"&&m.getattributenode("id");return m.nodetype===1&&p&&p.nodevalue===q}}l.removechild(g);l=g=null})();(function(){var g=s.createelement("div");g.appendchild(s.createcomment(""));if(g.getelementsbytagname("*").length>0)n.find.tag=function(h,l){l=l.getelementsbytagname(h[1]);if(h[1]==="*"){h=[];for(var m=0;l[m];m++)l[m].nodetype===1&&h.push(l[m]);l=h}return l};g.innerhtml="<a href='#'></a>";
if(g.firstchild&&typeof g.firstchild.getattribute!=="undefined"&&g.firstchild.getattribute("href")!=="#")n.attrhandle.href=function(h){return h.getattribute("href",2)};g=null})();s.queryselectorall&&function(){var g=k,h=s.createelement("div");h.innerhtml="<p class='test'></p>";if(!(h.queryselectorall&&h.queryselectorall(".test").length===0)){k=function(m,q,p,v){q=q||s;if(!v&&q.nodetype===9&&!x(q))try{return z(q.queryselectorall(m),p)}catch(t){}return g(m,q,p,v)};for(var l in g)k[l]=g[l];h=null}}();
(function(){var g=s.createelement("div");g.innerhtml="<div class='test e'></div><div class='test'></div>";if(!(!g.getelementsbyclassname||g.getelementsbyclassname("e").length===0)){g.lastchild.classname="e";if(g.getelementsbyclassname("e").length!==1){n.order.splice(1,0,"class");n.find.class=function(h,l,m){if(typeof l.getelementsbyclassname!=="undefined"&&!m)return l.getelementsbyclassname(h[1])};g=null}}})();var e=s.comparedocumentposition?function(g,h){return!!(g.comparedocumentposition(h)&16)}:
function(g,h){return g!==h&&(g.contains?g.contains(h):true)},x=function(g){return(g=(g?g.ownerdocument||g:0).documentelement)?g.nodename!=="html":false},ga=function(g,h){var l=[],m="",q;for(h=h.nodetype?[h]:h;q=n.match.pseudo.exec(g);){m+=q[0];g=g.replace(n.match.pseudo,"")}g=n.relative[g]?g+"*":g;q=0;for(var p=h.length;q<p;q++)k(g,h[q],l);return k.filter(m,l)};c.find=k;c.expr=k.selectors;c.expr[":"]=c.expr.filters;c.unique=k.uniquesort;c.text=a;c.isxmldoc=x;c.contains=e})();var eb=/until$/,fb=/^(?:parents|prevuntil|prevall)/,
gb=/,/;r=array.prototype.slice;var ia=function(a,b,d){if(c.isfunction(b))return c.grep(a,function(e,j){return!!b.call(e,j,e)===d});else if(b.nodetype)return c.grep(a,function(e){return e===b===d});else if(typeof b==="string"){var f=c.grep(a,function(e){return e.nodetype===1});if(ua.test(b))return c.filter(b,f,!d);else b=c.filter(b,f)}return c.grep(a,function(e){return c.inarray(e,b)>=0===d})};c.fn.extend({find:function(a){for(var b=this.pushstack("","find",a),d=0,f=0,e=this.length;f<e;f++){d=b.length;
c.find(a,this[f],b);if(f>0)for(var j=d;j<b.length;j++)for(var i=0;i<d;i++)if(b[i]===b[j]){b.splice(j--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,f=b.length;d<f;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushstack(ia(this,a,false),"not",a)},filter:function(a){return this.pushstack(ia(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>0},closest:function(a,b){if(c.isarray(a)){var d=[],f=this[0],e,j=
{},i;if(f&&a.length){e=0;for(var o=a.length;e<o;e++){i=a[e];j[i]||(j[i]=c.expr.match.pos.test(i)?c(i,b||this.context):i)}for(;f&&f.ownerdocument&&f!==b;){for(i in j){e=j[i];if(e.jquery?e.index(f)>-1:c(f).is(e)){d.push({selector:i,elem:f});delete j[i]}}f=f.parentnode}}return d}var k=c.expr.match.pos.test(a)?c(a,b||this.context):null;return this.map(function(n,r){for(;r&&r.ownerdocument&&r!==b;){if(k?k.index(r)>-1:c(r).is(a))return r;r=r.parentnode}return null})},index:function(a){if(!a||typeof a===
"string")return c.inarray(this[0],a?c(a):this.parent().children());return c.inarray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makearray(a);b=c.merge(this.get(),a);return this.pushstack(qa(a[0])||qa(b[0])?b:c.unique(b))},andself:function(){return this.add(this.prevobject)}});c.each({parent:function(a){return(a=a.parentnode)&&a.nodetype!==11?a:null},parents:function(a){return c.dir(a,"parentnode")},parentsuntil:function(a,b,d){return c.dir(a,"parentnode",
d)},next:function(a){return c.nth(a,2,"nextsibling")},prev:function(a){return c.nth(a,2,"previoussibling")},nextall:function(a){return c.dir(a,"nextsibling")},prevall:function(a){return c.dir(a,"previoussibling")},nextuntil:function(a,b,d){return c.dir(a,"nextsibling",d)},prevuntil:function(a,b,d){return c.dir(a,"previoussibling",d)},siblings:function(a){return c.sibling(a.parentnode.firstchild,a)},children:function(a){return c.sibling(a.firstchild)},contents:function(a){return c.nodename(a,"iframe")?
a.contentdocument||a.contentwindow.document:c.makearray(a.childnodes)}},function(a,b){c.fn[a]=function(d,f){var e=c.map(this,b,d);eb.test(a)||(f=d);if(f&&typeof f==="string")e=c.filter(f,e);e=this.length>1?c.unique(e):e;if((this.length>1||gb.test(f))&&fb.test(a))e=e.reverse();return this.pushstack(e,a,r.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return c.find.matches(a,b)},dir:function(a,b,d){var f=[];for(a=a[b];a&&a.nodetype!==9&&(d===w||a.nodetype!==1||!c(a).is(d));){a.nodetype===
1&&f.push(a);a=a[b]}return f},nth:function(a,b,d){b=b||1;for(var f=0;a;a=a[d])if(a.nodetype===1&&++f===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextsibling)a.nodetype===1&&a!==b&&d.push(a);return d}});var ja=/ jquery\d+="(?:\d+|null)"/g,v=/^\s+/,ka=/(<([\w:]+)[^>]*?)\/>/g,hb=/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i,la=/<([\w:]+)/,ib=/<tbody/i,jb=/<|&#?\w+;/,ta=/<script|<object|<embed|<option|<style/i,ua=/checked\s*(?:[^=]|=\s*.checked.)/i,ma=function(a,b,d){return hb.test(d)?
a:b+"></"+d+">"},f={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};f.optgroup=f.option;f.tbody=f.tfoot=f.colgroup=f.caption=f.thead;f.th=f.td;if(!c.support.htmlserialize)f._default=[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isfunction(a))return this.each(function(b){var d=
c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==w)return this.empty().append((this[0]&&this[0].ownerdocument||s).createtextnode(a));return c.text(this)},wrapall:function(a){if(c.isfunction(a))return this.each(function(d){c(this).wrapall(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerdocument).eq(0).clone(true);this[0].parentnode&&b.insertbefore(this[0]);b.map(function(){for(var d=this;d.firstchild&&d.firstchild.nodetype===1;)d=d.firstchild;return d}).append(this)}return this},
wrapinner:function(a){if(c.isfunction(a))return this.each(function(b){c(this).wrapinner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapall(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapall(a)})},unwrap:function(){return this.parent().each(function(){c.nodename(this,"body")||c(this).replacewith(this.childnodes)}).end()},append:function(){return this.dommanip(arguments,true,function(a){this.nodetype===1&&this.appendchild(a)})},
prepend:function(){return this.dommanip(arguments,true,function(a){this.nodetype===1&&this.insertbefore(a,this.firstchild)})},before:function(){if(this[0]&&this[0].parentnode)return this.dommanip(arguments,false,function(b){this.parentnode.insertbefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toarray());return this.pushstack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentnode)return this.dommanip(arguments,false,function(b){this.parentnode.insertbefore(b,
this.nextsibling)});else if(arguments.length){var a=this.pushstack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toarray());return a}},remove:function(a,b){for(var d=0,f;(f=this[d])!=null;d++)if(!a||c.filter(a,[f]).length){if(!b&&f.nodetype===1){c.cleandata(f.getelementsbytagname("*"));c.cleandata([f])}f.parentnode&&f.parentnode.removechild(f)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodetype===1&&c.cleandata(b.getelementsbytagname("*"));b.firstchild;)b.removechild(b.firstchild);
return this},clone:function(a){var b=this.map(function(){if(!c.support.nocloneevent&&!c.isxmldoc(this)){var d=this.outerhtml,f=this.ownerdocument;if(!d){d=f.createelement("div");d.appendchild(this.clonenode(true));d=d.innerhtml}return c.clean([d.replace(ja,"").replace(/=([^="'>\s]+\/)>/g,'="$1">').replace(v,"")],f)[0]}else return this.clonenode(true)});if(a===true){ra(this,b);ra(this.find("*"),b.find("*"))}return b},html:function(a){if(a===w)return this[0]&&this[0].nodetype===1?this[0].innerhtml.replace(ja,
""):null;else if(typeof a==="string"&&!ta.test(a)&&(c.support.leadingwhitespace||!v.test(a))&&!f[(la.exec(a)||["",""])[1].tolowercase()]){a=a.replace(ka,ma);try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodetype===1){c.cleandata(this[b].getelementsbytagname("*"));this[b].innerhtml=a}}catch(f){this.empty().append(a)}}else c.isfunction(a)?this.each(function(e){var j=c(this),i=j.html();j.empty().append(function(){return a.call(this,e,i)})}):this.empty().append(a);return this},replacewith:function(a){if(this[0]&&
this[0].parentnode){if(c.isfunction(a))return this.each(function(b){var d=c(this),f=d.html();d.replacewith(a.call(this,b,f))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextsibling,d=this.parentnode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushstack(c(c.isfunction(a)?a():a),"replacewith",a)},detach:function(a){return this.remove(a,true)},dommanip:function(a,b,d){function f(u){return c.nodename(u,"table")?u.getelementsbytagname("tbody")[0]||
u.appendchild(u.ownerdocument.createelement("tbody")):u}var e,j,i=a[0],o=[],k;if(!c.support.checkclone&&arguments.length===3&&typeof i==="string"&&ua.test(i))return this.each(function(){c(this).dommanip(a,b,d,true)});if(c.isfunction(i))return this.each(function(u){var z=c(this);a[0]=i.call(this,u,b?z.html():w);z.dommanip(a,b,d)});if(this[0]){e=i&&i.parentnode;e=c.support.parentnode&&e&&e.nodetype===11&&e.childnodes.length===this.length?{fragment:e}:sa(a,this,o);k=e.fragment;if(j=k.childnodes.length===
1?(k=k.firstchild):k.firstchild){b=b&&c.nodename(j,"tr");for(var n=0,r=this.length;n<r;n++)d.call(b?f(this[n],j):this[n],n>0||e.cacheable||this.length>1?k.clonenode(true):k)}o.length&&c.each(o,qa)}return this}});c.fragments={};c.each({appendto:"append",prependto:"prepend",insertbefore:"before",insertafter:"after",replaceall:"replacewith"},function(a,b){c.fn[a]=function(d){var f=[];d=c(d);var e=this.length===1&&this[0].parentnode;if(e&&e.nodetype===11&&e.childnodes.length===1&&d.length===1){d[b](this[0]);
return this}else{e=0;for(var j=d.length;e<j;e++){var i=(e>0?this.clone(true):this).get();c.fn[b].apply(c(d[e]),i);f=f.concat(i)}return this.pushstack(f,a,d.selector)}}});c.extend({clean:function(a,b,d,f){b=b||s;if(typeof b.createelement==="undefined")b=b.ownerdocument||b[0]&&b[0].ownerdocument||s;for(var e=[],j=0,i;(i=a[j])!=null;j++){if(typeof i==="number")i+="";if(i){if(typeof i==="string"&&!jb.test(i))i=b.createtextnode(i);else if(typeof i==="string"){i=i.replace(ka,ma);var o=(la.exec(i)||["",
""])[1].tolowercase(),k=f[o]||f._default,n=k[0],r=b.createelement("div");for(r.innerhtml=k[1]+i+k[2];n--;)r=r.lastchild;if(!c.support.tbody){n=ib.test(i);o=o==="table"&&!n?r.firstchild&&r.firstchild.childnodes:k[1]==="<table>"&&!n?r.childnodes:[];for(k=o.length-1;k>=0;--k)c.nodename(o[k],"tbody")&&!o[k].childnodes.length&&o[k].parentnode.removechild(o[k])}!c.support.leadingwhitespace&&v.test(i)&&r.insertbefore(b.createtextnode(v.exec(i)[0]),r.firstchild);i=r.childnodes}if(i.nodetype)e.push(i);else e=
c.merge(e,i)}}if(d)for(j=0;e[j];j++)if(f&&c.nodename(e[j],"script")&&(!e[j].type||e[j].type.tolowercase()==="text/javascript"))f.push(e[j].parentnode?e[j].parentnode.removechild(e[j]):e[j]);else{e[j].nodetype===1&&e.splice.apply(e,[j+1,0].concat(c.makearray(e[j].getelementsbytagname("script"))));d.appendchild(e[j])}return e},cleandata:function(a){for(var b,d,f=c.cache,e=c.event.special,j=c.support.deleteexpando,i=0,o;(o=a[i])!=null;i++)if(d=o[c.expando]){b=f[d];if(b.events)for(var k in b.events)e[k]?
c.event.remove(o,k):ca(o,k,b.handle);if(j)delete o[c.expando];else o.removeattribute&&o.removeattribute(c.expando);delete f[d]}}});var kb=/z-?index|font-?weight|opacity|zoom|line-?height/i,na=/alpha\([^)]*\)/,oa=/opacity=([^)]*)/,ha=/float/i,ia=/-([a-z])/ig,lb=/([a-z])/g,mb=/^-?\d+(?:px)?$/i,nb=/^-?\d/,ob={position:"absolute",visibility:"hidden",display:"block"},pb=["left","right"],qb=["top","bottom"],rb=s.defaultview&&s.defaultview.getcomputedstyle,pa=c.support.cssfloat?"cssfloat":"stylefloat",ja=
function(a,b){return b.touppercase()};c.fn.css=function(a,b){return x(this,a,b,true,function(d,f,e){if(e===w)return c.curcss(d,f);if(typeof e==="number"&&!kb.test(f))e+="px";c.style(d,f,e)})};c.extend({style:function(a,b,d){if(!a||a.nodetype===3||a.nodetype===8)return w;if((b==="width"||b==="height")&&parsefloat(d)<0)d=w;var f=a.style||a,e=d!==w;if(!c.support.opacity&&b==="opacity"){if(e){f.zoom=1;b=parseint(d,10)+""==="nan"?"":"alpha(opacity="+d*100+")";a=f.filter||c.curcss(a,"filter")||"";f.filter=
na.test(a)?a.replace(na,b):b}return f.filter&&f.filter.indexof("opacity=")>=0?parsefloat(oa.exec(f.filter)[1])/100+"":""}if(ha.test(b))b=pa;b=b.replace(ia,ja);if(e)f[b]=d;return f[b]},css:function(a,b,d,f){if(b==="width"||b==="height"){var e,j=b==="width"?pb:qb;function i(){e=b==="width"?a.offsetwidth:a.offsetheight;f!=="border"&&c.each(j,function(){f||(e-=parsefloat(c.curcss(a,"padding"+this,true))||0);if(f==="margin")e+=parsefloat(c.curcss(a,"margin"+this,true))||0;else e-=parsefloat(c.curcss(a,
"border"+this+"width",true))||0})}a.offsetwidth!==0?i():c.swap(a,ob,i);return math.max(0,math.round(e))}return c.curcss(a,b,d)},curcss:function(a,b,d){var f,e=a.style;if(!c.support.opacity&&b==="opacity"&&a.currentstyle){f=oa.test(a.currentstyle.filter||"")?parsefloat(regexp.$1)/100+"":"";return f===""?"1":f}if(ha.test(b))b=pa;if(!d&&e&&e[b])f=e[b];else if(rb){if(ha.test(b))b="float";b=b.replace(lb,"-$1").tolowercase();e=a.ownerdocument.defaultview;if(!e)return null;if(a=e.getcomputedstyle(a,null))f=
a.getpropertyvalue(b);if(b==="opacity"&&f==="")f="1"}else if(a.currentstyle){d=b.replace(ia,ja);f=a.currentstyle[b]||a.currentstyle[d];if(!mb.test(f)&&nb.test(f)){b=e.left;var j=a.runtimestyle.left;a.runtimestyle.left=a.currentstyle.left;e.left=d==="fontsize"?"1em":f||0;f=e.pixelleft+"px";e.left=b;a.runtimestyle.left=j}}return f},swap:function(a,b,d){var f={};for(var e in b){f[e]=a.style[e];a.style[e]=b[e]}d.call(a);for(e in b)a.style[e]=f[e]}});if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=
a.offsetwidth,d=a.offsetheight,f=a.nodename.tolowercase()==="tr";return b===0&&d===0&&!f?true:b>0&&d>0&&!f?false:c.curcss(a,"display")==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var sb=j(),tb=/<script(.|\s)*?\/script>/gi,ub=/select|textarea/i,vb=/color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week/i,n=/=\?(&|$)/,ka=/\?/,wb=/(\?|&)_=.*?(&|$)/,xb=/^(\w+:)?\/\/([^\/?#]+)/,yb=/%20/g,zb=c.fn.load;c.fn.extend({load:function(a,b,d){if(typeof a!==
"string")return zb.call(this,a);else if(!this.length)return this;var f=a.indexof(" ");if(f>=0){var e=a.slice(f,a.length);a=a.slice(0,f)}f="get";if(b)if(c.isfunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxsettings.traditional);f="post"}var j=this;c.ajax({url:a,type:f,datatype:"html",data:b,complete:function(i,o){if(o==="success"||o==="notmodified")j.html(e?c("<div />").append(i.responsetext.replace(tb,"")).find(e):i.responsetext);d&&j.each(d,[i.responsetext,o,i])}});return this},
serialize:function(){return c.param(this.serializearray())},serializearray:function(){return this.map(function(){return this.elements?c.makearray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||ub.test(this.nodename)||vb.test(this.type))}).map(function(a,b){a=c(this).val();return a==null?null:c.isarray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxstart ajaxstop ajaxcomplete ajaxerror ajaxsuccess ajaxsend".split(" "),
function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,f){if(c.isfunction(b)){f=f||d;d=b;b=null}return c.ajax({type:"get",url:a,data:b,success:d,datatype:f})},getscript:function(a,b){return c.get(a,null,b,"script")},getjson:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,b,d,f){if(c.isfunction(b)){f=f||d;d=b;b={}}return c.ajax({type:"post",url:a,data:b,success:d,datatype:f})},ajaxsetup:function(a){c.extend(c.ajaxsettings,a)},ajaxsettings:{url:location.href,
global:true,type:"get",contenttype:"application/x-www-form-urlencoded",processdata:true,async:true,xhr:a.xmlhttprequest&&(a.location.protocol!=="file:"||!a.activexobject)?function(){return new a.xmlhttprequest}:function(){try{return new a.activexobject("microsoft.xmlhttp")}catch(a){}},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},lastmodified:{},etag:{},ajax:function(a){function b(){e.success&&
e.success.call(k,o,i,x);e.global&&f("ajaxsuccess",[x,e])}function d(){e.complete&&e.complete.call(k,x,i);e.global&&f("ajaxcomplete",[x,e]);e.global&&!--c.active&&c.event.trigger("ajaxstop")}function f(q,p){(e.context?c(e.context):c.event).trigger(q,p)}var e=c.extend(true,{},c.ajaxsettings,a),j,i,o,k=a&&a.context||e,n=e.type.touppercase();if(e.data&&e.processdata&&typeof e.data!=="string")e.data=c.param(e.data,e.traditional);if(e.datatype==="jsonp"){if(n==="get")n.test(e.url)||(e.url+=(ka.test(e.url)?
"&":"?")+(e.jsonp||"callback")+"=?");else if(!e.data||!n.test(e.data))e.data=(e.data?e.data+"&":"")+(e.jsonp||"callback")+"=?";e.datatype="json"}if(e.datatype==="json"&&(e.data&&n.test(e.data)||n.test(e.url))){j=e.jsonpcallback||"jsonp"+sb++;if(e.data)e.data=(e.data+"").replace(n,"="+j+"$1");e.url=e.url.replace(n,"="+j+"$1");e.datatype="script";a[j]=a[j]||function(q){o=q;b();d();a[j]=w;try{delete a[j]}catch(p){}z&&z.removechild(c)}}if(e.datatype==="script"&&e.cache===null)e.cache=false;if(e.cache===
false&&n==="get"){var r=j(),u=e.url.replace(wb,"$1_="+r+"$2");e.url=u+(u===e.url?(ka.test(e.url)?"&":"?")+"_="+r:"")}if(e.data&&n==="get")e.url+=(ka.test(e.url)?"&":"?")+e.data;e.global&&!c.active++&&c.event.trigger("ajaxstart");r=(r=xb.exec(e.url))&&(r[1]&&r[1]!==location.protocol||r[2]!==location.host);if(e.datatype==="script"&&n==="get"&&r){var z=s.getelementsbytagname("head")[0]||s.documentelement,c=s.createelement("script");c.src=e.url;if(e.scriptcharset)c.charset=e.scriptcharset;if(!j){var b=
false;c.onload=c.onreadystatechange=function(){if(!b&&(!this.readystate||this.readystate==="loaded"||this.readystate==="complete")){b=true;b();d();c.onload=c.onreadystatechange=null;z&&c.parentnode&&z.removechild(c)}}}z.insertbefore(c,z.firstchild);return w}var e=false,x=e.xhr();if(x){e.username?x.open(n,e.url,e.async,e.username,e.password):x.open(n,e.url,e.async);try{if(e.data||a&&a.contenttype)x.setrequestheader("content-type",e.contenttype);if(e.ifmodified){c.lastmodified[e.url]&&x.setrequestheader("if-modified-since",
c.lastmodified[e.url]);c.etag[e.url]&&x.setrequestheader("if-none-match",c.etag[e.url])}r||x.setrequestheader("x-requested-with","xmlhttprequest");x.setrequestheader("accept",e.datatype&&e.accepts[e.datatype]?e.accepts[e.datatype]+", */*":e.accepts._default)}catch(ga){}if(e.beforesend&&e.beforesend.call(k,x,e)===false){e.global&&!--c.active&&c.event.trigger("ajaxstop");x.abort();return false}e.global&&f("ajaxsend",[x,e]);var g=x.onreadystatechange=function(q){if(!x||x.readystate===0||q==="abort"){e||
d();e=true;if(x)x.onreadystatechange=c.noop}else if(!e&&x&&(x.readystate===4||q==="timeout")){e=true;x.onreadystatechange=c.noop;i=q==="timeout"?"timeout":!c.httpsuccess(x)?"error":e.ifmodified&&c.httpnotmodified(x,e.url)?"notmodified":"success";var p;if(i==="success")try{o=c.httpdata(x,e.datatype,e)}catch(v){i="parsererror";p=v}if(i==="success"||i==="notmodified")j||b();else c.handleerror(e,x,i,p);d();q==="timeout"&&x.abort();if(e.async)x=null}};try{var h=x.abort;x.abort=function(){x&&h.call(x);
g("abort")}}catch(l){}e.async&&e.timeout>0&&settimeout(function(){x&&!e&&g("timeout")},e.timeout);try{x.send(n==="post"||n==="put"||n==="delete"?e.data:null)}catch(m){c.handleerror(e,x,null,m);d()}e.async||g();return x}},handleerror:function(a,b,d,f){if(a.error)a.error.call(a.context||a,b,d,f);if(a.global)(a.context?c(a.context):c.event).trigger("ajaxerror",[b,a,f])},active:0,httpsuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===
1223||a.status===0}catch(b){}return false},httpnotmodified:function(a,b){var d=a.getresponseheader("last-modified"),f=a.getresponseheader("etag");if(d)c.lastmodified[b]=d;if(f)c.etag[b]=f;return a.status===304||a.status===0},httpdata:function(a,b,d){var f=a.getresponseheader("content-type")||"",e=b==="xml"||!b&&f.indexof("xml")>=0;a=e?a.responsexml:a.responsetext;e&&a.documentelement.nodename==="parsererror"&&c.error("parsererror");if(d&&d.datafilter)a=d.datafilter(a,b);if(typeof a==="string")if(b===
"json"||!b&&f.indexof("json")>=0)a=c.parsejson(a);else if(b==="script"||!b&&f.indexof("javascript")>=0)c.globaleval(a);return a},param:function(a,b){function d(i,o){if(c.isarray(o))c.each(o,function(k,n){b||/\[\]$/.test(i)?f(i,n):d(i+"["+(typeof n==="object"||c.isarray(n)?k:"")+"]",n)});else!b&&o!=null&&typeof o==="object"?c.each(o,function(k,n){d(i+"["+k+"]",n)}):f(i,o)}function f(i,o){o=c.isfunction(o)?o():o;e[e.length]=encodeuricomponent(i)+"="+encodeuricomponent(o)}var e=[];if(b===w)b=c.ajaxsettings.traditional;
if(c.isarray(a)||a.jquery)c.each(a,function(){f(this.name,this.value)});else for(var j in a)d(j,a[j]);return e.join("&").replace(yb,"+")}});var la={},ab=/toggle|show|hide/,bb=/^([+-]=)?([\d+-.]+)(.*)$/,w,va=[["height","margintop","marginbottom","paddingtop","paddingbottom"],["width","marginleft","marginright","paddingleft","paddingright"],["opacity"]];c.fn.extend({show:function(a,b){if(a||a===0)return this.animate(k("show",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");
this[a].style.display=d||"";if(c.css(this[a],"display")==="none"){d=this[a].nodename;var f;if(la[d])f=la[d];else{var e=c("<"+d+" />").appendto("body");f=e.css("display");if(f==="none")f="block";e.remove();la[d]=f}c.data(this[a],"olddisplay",f)}}a=0;for(b=this.length;a<b;a++)this[a].style.display=c.data(this[a],"olddisplay")||"";return this}},hide:function(a,b){if(a||a===0)return this.animate(k("hide",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");!d&&d!=="none"&&c.data(this[a],
"olddisplay",c.css(this[a],"display"))}a=0;for(b=this.length;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b){var d=typeof a==="boolean";if(c.isfunction(a)&&c.isfunction(b))this._toggle.apply(this,arguments);else a==null||d?this.each(function(){var f=d?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate(k("toggle",3),a,b);return this},fadeto:function(a,b,d){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d)},
animate:function(a,b,d,f){var e=c.speed(b,d,f);if(c.isemptyobject(a))return this.each(e.complete);return this[e.queue===false?"each":"queue"](function(){var j=c.extend({},e),i,o=this.nodetype===1&&c(this).is(":hidden"),k=this;for(i in a){var n=i.replace(ia,ja);if(i!==n){a[n]=a[i];delete a[i];i=n}if(a[i]==="hide"&&o||a[i]==="show"&&!o)return j.complete.call(this);if((i==="height"||i==="width")&&this.style){j.display=c.css(this,"display");j.overflow=this.style.overflow}if(c.isarray(a[i])){(j.specialeasing=
j.specialeasing||{})[i]=a[i][1];a[i]=a[i][0]}}if(j.overflow!=null)this.style.overflow="hidden";j.curanim=c.extend({},a);c.each(a,function(r,u){var z=new c.fx(k,j,r);if(ab.test(u))z[u==="toggle"?o?"show":"hide":u](a);else{var c=bb.exec(u),b=z.cur(true)||0;if(c){u=parsefloat(c[2]);var e=c[3]||"px";if(e!=="px"){k.style[r]=(u||1)+e;b=(u||1)/z.cur(true)*b;k.style[r]=b+e}if(c[1])u=(c[1]==="-="?-1:1)*u+b;z.custom(b,u,e)}else z.custom(b,u,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);
this.each(function(){for(var f=d.length-1;f>=0;f--)if(d[f].elem===this){b&&d[f](true);d.splice(f,1)}});b||this.dequeue();return this}});c.each({slidedown:k("show",1),slideup:k("hide",1),slidetoggle:k("toggle",1),fadein:{opacity:"show"},fadeout:{opacity:"hide"}},function(a,b){c.fn[a]=function(d,f){return this.animate(b,d,f)}});c.extend({speed:function(a,b,d){var f=a&&typeof a==="object"?a:{complete:d||!d&&b||c.isfunction(a)&&a,duration:a,easing:d&&b||b&&!c.isfunction(b)&&b};f.duration=c.fx.off?0:typeof f.duration===
"number"?f.duration:c.fx.speeds[f.duration]||c.fx.speeds._default;f.old=f.complete;f.complete=function(){f.queue!==false&&c(this).dequeue();c.isfunction(f.old)&&f.old.call(this)};return f},easing:{linear:function(a,b,d,f){return d+f*a},swing:function(a,b,d,f){return(-math.cos(a*math.pi)/2+0.5)*f+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||
c.fx.step._default)(this);if((this.prop==="height"||this.prop==="width")&&this.elem.style)this.elem.style.display="block"},cur:function(a){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];return(a=parsefloat(c.css(this.elem,this.prop,a)))&&a>-10000?a:parsefloat(c.curcss(this.elem,this.prop))||0},custom:function(a,b,d){function f(j){return e.step(j)}this.starttime=j();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;
this.pos=this.state=0;var e=this;f.elem=this.elem;if(f()&&c.timers.push(f)&&!w)w=setinterval(c.fx.tick,13)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=j(),d=true;if(a||b>=this.options.duration+this.starttime){this.now=
this.end;this.pos=this.state=1;this.update();this.options.curanim[this.prop]=true;for(var f in this.options.curanim)if(this.options.curanim[f]!==true)d=false;if(d){if(this.options.display!=null){this.elem.style.overflow=this.options.overflow;a=c.data(this.elem,"olddisplay");this.elem.style.display=a?a:this.options.display;if(c.css(this.elem,"display")==="none")this.elem.style.display="block"}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var e in this.options.curanim)c.style(this.elem,
e,this.options.orig[e]);this.options.complete.call(this.elem)}return false}else{e=b-this.starttime;this.state=e/this.options.duration;a=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialeasing&&this.options.specialeasing[this.prop]||a](this.state,e,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||
c.fx.stop()},stop:function(){clearinterval(w);w=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};c.fn.offset="getboundingclientrect"in s.documentelement?
function(a){var b=this[0];if(a)return this.each(function(e){c.offset.setoffset(this,a,e)});if(!b||!b.ownerdocument)return null;if(b===b.ownerdocument.body)return c.offset.bodyoffset(b);var d=b.getboundingclientrect(),f=b.ownerdocument;b=f.body;f=f.documentelement;return{top:d.top+(self.pageyoffset||c.support.boxmodel&&f.scrolltop||b.scrolltop)-(f.clienttop||b.clienttop||0),left:d.left+(self.pagexoffset||c.support.boxmodel&&f.scrollleft||b.scrollleft)-(f.clientleft||b.clientleft||0)}}:function(a){var b=
this[0];if(a)return this.each(function(r){c.offset.setoffset(this,a,r)});if(!b||!b.ownerdocument)return null;if(b===b.ownerdocument.body)return c.offset.bodyoffset(b);c.offset.initialize();var d=b.offsetparent,f=b,e=b.ownerdocument,j,i=e.documentelement,o=e.body;f=(e=e.defaultview)?e.getcomputedstyle(b,null):b.currentstyle;for(var k=b.offsettop,n=b.offsetleft;(b=b.parentnode)&&b!==o&&b!==i;){if(c.offset.supportsfixedposition&&f.position==="fixed")break;j=e?e.getcomputedstyle(b,null):b.currentstyle;
k-=b.scrolltop;n-=b.scrollleft;if(b===d){k+=b.offsettop;n+=b.offsetleft;if(c.offset.doesnotaddborder&&!(c.offset.doesaddborderfortableandcells&&/^t(able|d|h)$/i.test(b.nodename))){k+=parsefloat(j.bordertopwidth)||0;n+=parsefloat(j.borderleftwidth)||0}f=d;d=b.offsetparent}if(c.offset.subtractsborderforoverflownotvisible&&j.overflow!=="visible"){k+=parsefloat(j.bordertopwidth)||0;n+=parsefloat(j.borderleftwidth)||0}f=j}if(f.position==="relative"||f.position==="static"){k+=o.offsettop;n+=o.offsetleft}if(c.offset.supportsfixedposition&&
f.position==="fixed"){k+=math.max(i.scrolltop,o.scrolltop);n+=math.max(i.scrollleft,o.scrollleft)}return{top:k,left:n}};c.offset={initialize:function(){var a=s.body,b=s.createelement("div"),d,f,e,j=parsefloat(c.curcss(a,"margintop",true))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerhtml="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
a.insertbefore(b,a.firstchild);d=b.firstchild;f=d.firstchild;e=d.nextsibling.firstchild.firstchild;this.doesnotaddborder=f.offsettop!==5;this.doesaddborderfortableandcells=e.offsettop===5;f.style.position="fixed";f.style.top="20px";this.supportsfixedposition=f.offsettop===20||f.offsettop===15;f.style.position=f.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsborderforoverflownotvisible=f.offsettop===-5;this.doesnotincludemargininbodyoffset=a.offsettop!==j;a.removechild(b);
c.offset.initialize=c.noop},bodyoffset:function(a){var b=a.offsettop,d=a.offsetleft;c.offset.initialize();if(c.offset.doesnotincludemargininbodyoffset){b+=parsefloat(c.curcss(a,"margintop",true))||0;d+=parsefloat(c.curcss(a,"marginleft",true))||0}return{top:b,left:d}},setoffset:function(a,b,d){if(/static/.test(c.curcss(a,"position")))a.style.position="relative";var f=c(a),e=f.offset(),j=parseint(c.curcss(a,"top",true),10)||0,i=parseint(c.curcss(a,"left",true),10)||0;if(c.isfunction(b))b=b.call(a,
d,e);d={top:b.top-e.top+j,left:b.left-e.left+i};"using"in b?b.using.call(a,d):f.css(d)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetparent(),d=this.offset(),f=/^body|html$/i.test(b[0].nodename)?{top:0,left:0}:b.offset();d.top-=parsefloat(c.curcss(a,"margintop",true))||0;d.left-=parsefloat(c.curcss(a,"marginleft",true))||0;f.top+=parsefloat(c.curcss(b[0],"bordertopwidth",true))||0;f.left+=parsefloat(c.curcss(b[0],"borderleftwidth",true))||0;return{top:d.top-
f.top,left:d.left-f.left}},offsetparent:function(){return this.map(function(){for(var a=this.offsetparent||s.body;a&&!/^body|html$/i.test(a.nodename)&&c.css(a,"position")==="static";)a=a.offsetparent;return a})}});c.each(["left","top"],function(a,b){var d="scroll"+b;c.fn[d]=function(f){var e=this[0],j;if(!e)return null;if(f!==w)return this.each(function(){if(j=wa(this))j.scrollto(!a?f:c(j).scrollleft(),a?f:c(j).scrolltop());else this[d]=f});else return(j=wa(e))?"pagexoffset"in j?j[a?"pageyoffset":
"pagexoffset"]:c.support.boxmodel&&j.document.documentelement[d]||j.document.body[d]:e[d]}});c.each(["height","width"],function(a,b){var d=b.tolowercase();c.fn["inner"+b]=function(){return this[0]?c.css(this[0],d,false,"padding"):null};c.fn["outer"+b]=function(f){return this[0]?c.css(this[0],d,false,f?"margin":"border"):null};c.fn[d]=function(f){var e=this[0];if(!e)return f==null?null:this;if(c.isfunction(f))return this.each(function(j){var i=c(this);i[d](f.call(this,j,i[d]()))});return"scrollto"in
e&&e.document?e.document.compatmode==="css1compat"&&e.document.documentelement["client"+b]||e.document.body["client"+b]:e.nodetype===9?math.max(e.documentelement["client"+b],e.body["scroll"+b],e.documentelement["scroll"+b],e.body["offset"+b],e.documentelement["offset"+b]):f===w?c.css(e,d):this.css(d,typeof f==="string"?f:f+"px")}});a.jquery=a.$=c})(window);
